<?php
  $pdf = new FFPDF('P','cm', 'A4');
  $InterLigne = 0.75;
  $pdf->SetTitle('Surat Pengantar');
  $tgl = 'Cisalak '.date("l,d F Y");
  $pdf->SetMargins(2,1,2);
  $pdf->AddPage();
  $pdf->SetFont('Arial','B',14);
  $pdf->Image('assets/index.jpg',1,1,2,2);
  $pdf->SetX(3);
 $pdf->MultiCell(15.5,0.5,'PENGURUS RUKUN TETANGGA',0,'C');
 $pdf->SetX(3);
 $pdf->MultiCell(15.5,0.5,'KELURAHAN CISALAK PASAR',0,'C');
 $pdf->SetFont('Arial','B',14);
 $pdf->SetX(3);
 $pdf->MultiCell(15.5,0.5,'KECAMATAN CIMANGGIS KOTA DEPOK',0,'C');
 $pdf->Line(1,3.1,20.5,3.1);
 $pdf->SetLineWidth(0.1);
 $pdf->Line(1,3.2,20.5,3.2);
 $pdf->SetLineWidth(0);
 $pdf->Ln();
 $pdf->Ln();
 $pdf->SetXY(3,4);
 $pdf->MultiCell(15.5,0.5,'SURAT'.' '.$cetak[0]['jenissurat'],0,'C');
 $pdf->Ln();
 $pdf->SetFont('Arial','',13);
 $txt = "                                                           Yang bertanda tangan di bawah ini, Ketua RT 04 RW 03 Kelurahan Cisalak Pasar Kecamatan Cimanggis Depok dengan ini menyatakan:";
 $pdf->MultiCell(0,$InterLigne,$txt,0,'J',0,10);
 $pdf->Ln();
 $pdf->SetFont('Arial','',11);
 $pdf->Cell(4, 0.75, 'NAMA', 0,0,'L');
 $pdf->Cell(0.15, 0.75, ':', 0,0,'L');
 $pdf->Cell(6, 0.75, $cetak[0]['nama'], 0,0,'L');
 $pdf->Ln();
 $pdf->Cell(4, 0.75, 'No KTP', 0,0,'L');
 $pdf->Cell(0.15, 0.75, ':', 0,0,'L');
 $pdf->Cell(3, 0.75, $cetak[0]['nik'], 0,0,'L');
 $pdf->Ln();
 $pdf->Cell(4, 0.75, 'Pekerjaan', 0,0,'L');
 $pdf->Cell(0.15, 0.75, ':', 0,0,'L');
 $pdf->Cell(3, 0.75, $cetak[0]['pekerjaan'], 0,0,'L');
 $pdf->Ln();
 $pdf->Cell(4, 0.75, 'TTL', 0,0,'L');
 $pdf->Cell(0.15, 0.75, ':', 0,0,'L');
 $pdf->Cell(2, 0.75, $cetak[0]['tempat_lahir'], 0,0,'L');
 $pdf->Cell(0.15, 0.75, '/', 0,0,'L');
 $pdf->Cell(3, 0.75, $cetak[0]['tanggal_lahir'], 0,0,'L');
 $pdf->Ln();
 $pdf->Cell(4, 0.75, 'Kewarganegaraan', 0,0,'L');
 $pdf->Cell(0.15, 0.75, ':', 0,0,'L');
 $pdf->Cell(3, 0.75, $cetak[0]['kewarganegaraan'], 0,0,'L');
 $pdf->Ln();
 $pdf->Cell(4, 0.75, 'Alamat', 0,0,'L');
 $pdf->Cell(0.15, 0.75, ':', 0,0,'L');
 $pdf->Cell(3, 0.75, $cetak[0]['alamat'], 0,0,'L');
 $pdf->Ln();
 $pdf->Ln();
 $pdf->SetFont('Arial','',13);
 $pdf->write(0.75,'Nama diatas adalah penduduk yang bermaksud :');
 $pdf->Ln();
 $pdf->Ln();
 $pdf->SetFont('Arial','',11);
 $pdf->write(0.75, $cetak[0]['ket'].'....');
 $pdf->Ln();
 $pdf->Cell(5, 0.75, '.....................................................................................................................................', 0,0,'L');
 $pdf->Ln();
 $pdf->Cell(4, 0.75, 'Bertempat Di :', 0,0,'L');
 $pdf->Ln();
 $pdf->Cell(5, 0.75, $cetak[0]['tempat'].'....', 0,0,'L');
 $pdf->Ln();
 $pdf->Cell(5, 0.75, '.....................................................................................................................................', 0,0,'L');
 $pdf->Ln();
 $pdf->Ln();
 $pdf->write(0.75,'Demikian surat pengantar ini diberikan untuk dipergunakan sebagaimana mestinya ');
 $pdf->Ln();
 $pdf->Ln();
 $pdf->SetX(3);
 $pdf->MultiCell(15.5,0.5,'Mengetahui',0,'C');
 $pdf->Ln();
 $pdf->Cell(10,0.5,$tgl,0,'R');
 $pdf->Ln();
 $pdf->Cell(12,0.5,'Ketua RW 03',0,'L');
 $pdf->Cell(12,0.5,'Ketua RT 04',0,'L');
 $pdf->Ln();
 $pdf->Ln();
 $pdf->Ln();
 $pdf->Ln();
 $pdf->Cell(12,0.5,'(SIDIK SOEWARTO, S.ak)',0,'L');
 $pdf->Cell(12,0.5,'(H. CECEP)',0,'L');
 $pdf->Output();
